  
name: sonar-csharp
env: 
  SONAR_ORG: kudadigital
  SONAR_PROJECT: sonar_icap_csharp
on:
  push:
    branches: '*'
    paths:
      - 'cloud-proxy-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cloud-proxy-app/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container: glasswallsolutions/icap-cs-base:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            submodules: true

        - name: scan csharp code
          run: |
            /root/.dotnet/tools/dotnet-sonarscanner begin   /o:"${{ env.SONAR_ORG }}"  /d:sonar.login="${{ secrets.SONAR_TOKEN }}"  /k:"${{ env.SONAR_PROJECT }}"  /d:sonar.host.url=https://sonarcloud.io /d:sonar.cfamily.build-wrapper-output="build_wrapper_output_directory"
            dotnet build cloud-proxy-app/cloud-proxy-app.sln
            /root/.dotnet/tools/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
